# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b2ffce92c70cd4d2ebfbaed9b1ec09d2e69b0f751662a69684659d35327246719fe6f49ec889dc63264a63276482c23a2a2c34fc8899cb8437b4686c46141e4

test:
  secret_key_base: ee7cb9fbbbf82ccf2e1a620d55d651941daee59e73f65dfe858b16861868bebbb582be77cd10267bedac198892db635ec348fb8e6e789205dd21921832ac722c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
